# Generated by Django 5.2.17 on 2026-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='balance_tiyin',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hisob raqam'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_mfo',
            field=models.CharField(blank=True, max_length=5, verbose_name='MFO'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('legal', 'Yuridik shaxs'), ('sole', 'YaTT (yakka tartibdagi tadbirkor)'), ('person', 'Jismoniy shaxs')], max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='is_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legal name / full name'),
        ),
        migrations.AddField(
            model_name='company',
            name='oked',
            field=models.CharField(blank=True, max_length=10, verbose_name='OKED'),
        ),
        migrations.AddField(
            model_name='company',
            name='overdue_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='paid_payment_units',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='paid_sms_units',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, verbose_name='JShShIR / PINFL'),
        ),
    ]
