# Generated by Django 5.2.17 on 2026-09-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_single_session_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
