# Generated by Django 5.2.17 on 2026-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_billing_exempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handofftoken',
            options={'verbose_name': 'handoff token', 'verbose_name_plural': 'handoff tokens'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_seen'], 'verbose_name': 'signed-in device', 'verbose_name_plural': 'signed-in devices'},
        ),
    ]
