# Generated by Django 5.2.17 on 2026-09-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
