# Generated by Django 5.2.17 on 2026-09-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blocked_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='paid_docs_units',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
