# Generated by Django 5.2.17 on 2026-09-24 12:56

import core.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0003_invoice_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('eskiz', 'Eskiz'), ('playmobile', 'Playmobile')], max_length=12)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('login', models.CharField(blank=True, max_length=150)),
                ('secret', core.crypto.EncryptedTextField(blank=True)),
                ('sender', models.CharField(blank=True, max_length=11)),
                ('token', core.crypto.EncryptedTextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('balance', models.CharField(blank=True, max_length=32)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_accounts', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('eskiz', 'Eskiz'), ('playmobile', 'Playmobile')], max_length=12)),
                ('external_id', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField()),
                ('status', models.CharField(default='local', max_length=16)),
                ('amo_enum_id', models.BigIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='accounts.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, choices=[('eskiz', 'Eskiz'), ('playmobile', 'Playmobile')], max_length=12)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_settings', to='accounts.company')),
                ('link_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms.smstemplate')),
                ('paid_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms.smstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('eskiz', 'Eskiz'), ('playmobile', 'Playmobile')], max_length=12)),
                ('phone', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('event', models.CharField(choices=[('manual', 'Manual'), ('link', 'Payment link'), ('amocrm', 'From amoCRM'), ('paid', 'Payment received')], default='manual', max_length=10)),
                ('lead_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_status', models.CharField(blank=True, max_length=32)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='sms.smsaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='accounts.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms', to='payments.invoice')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms.smstemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='smsaccount',
            constraint=models.UniqueConstraint(fields=('company', 'provider'), name='uniq_sms_account'),
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('company', 'provider', 'external_id'), name='uniq_sms_template_external'),
        ),
    ]
