# Generated by Django 5.2.17 on 2026-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='external_ref',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='smsmessage',
            name='event',
            field=models.CharField(choices=[('manual', 'Manual'), ('link', 'Payment link'), ('amocrm', 'From amoCRM'), ('api', 'API / Odoo'), ('paid', 'Payment received')], default='manual', max_length=10),
        ),
    ]
