# Generated by Django 5.2.17 on 2026-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smsmessage_external_ref_alter_smsmessage_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='use_in_amocrm',
            field=models.BooleanField(default=True),
        ),
    ]
