# Generated by Django 5.2.17 on 2026-09-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_single_session_usersession'),
        ('sms', '0003_amocrm_widget_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(choices=[('amocrm', 'amoCRM'), ('odoo', 'Odoo')], max_length=10)),
                ('key', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_variables', to='accounts.company')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('company', 'integration', 'key'), name='uniq_sms_variable_key')],
            },
        ),
    ]
