# Generated by Django 5.2.17 on 2026-09-24 17:27

import django.db.models.deletion
from django.db import migrations, models


def link_templates(apps, schema_editor):
    """Templates and the default gateway were per provider; now they point at an account."""
    Account = apps.get_model("sms", "SmsAccount")
    Template = apps.get_model("sms", "SmsTemplate")
    Settings = apps.get_model("sms", "SmsSettings")
    for acc in Account.objects.all():
        Template.objects.filter(company_id=acc.company_id, provider=acc.provider, account=None).update(account=acc)
    for st in Settings.objects.exclude(provider=""):
        st.account = Account.objects.filter(company_id=st.company_id, provider=st.provider).first()
        st.save(update_fields=["account"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_single_session_usersession'),
        ('sms', '0004_sms_variables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsaccount',
            options={'ordering': ['created_at', 'pk']},
        ),
        migrations.RemoveConstraint(
            model_name='smsaccount',
            name='uniq_sms_account',
        ),
        migrations.RemoveConstraint(
            model_name='smstemplate',
            name='uniq_sms_template_external',
        ),
        migrations.AddField(
            model_name='smsaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='smsaccount',
            name='label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms.smsaccount'),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='sms.smsaccount'),
        ),
        migrations.AlterField(
            model_name='smsaccount',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(link_templates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('account', 'external_id'), name='uniq_sms_template_external'),
        ),
    ]
