# Generated by Django 5.2.17 on 2026-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_multi_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsaccount',
            options={'ordering': ['created_at', 'pk'], 'verbose_name': 'SMS account', 'verbose_name_plural': 'SMS accounts'},
        ),
        migrations.AlterModelOptions(
            name='smsmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS message', 'verbose_name_plural': 'SMS messages'},
        ),
        migrations.AlterModelOptions(
            name='smssettings',
            options={'verbose_name': 'SMS settings', 'verbose_name_plural': 'SMS settings'},
        ),
        migrations.AlterModelOptions(
            name='smstemplate',
            options={'ordering': ['id'], 'verbose_name': 'SMS template', 'verbose_name_plural': 'SMS templates'},
        ),
        migrations.AlterModelOptions(
            name='smsvariable',
            options={'ordering': ['key'], 'verbose_name': 'SMS keyword', 'verbose_name_plural': 'SMS keywords'},
        ),
    ]
