# Generated by Django 5.2.17 on 2026-09-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_company_balance_tiyin_company_bank_account_and_more'),
        ('payments', '0005_alter_invoice_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Top-up'), ('charge', 'Subscription'), ('prorata', 'Added mid-period'), ('credit', 'Manual credit'), ('adjust', 'Adjustment')], max_length=10)),
                ('amount_tiyin', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='accounts.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
