# Generated by Django 5.2.17 on 2026-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'ledger entry', 'verbose_name_plural': 'ledger entries'},
        ),
    ]
