# Generated by Django 5.2.17 on 2026-09-24 18:38

import django.db.models.deletion
from django.db import migrations, models


def seed_prices(apps, schema_editor):
    """Today's prices, now editable in the admin."""
    TariffPrice = apps.get_model("billing", "TariffPrice")
    for kind, first, extra in (("payment", 500_000, 200_000), ("sms", 300_000, 100_000)):
        TariffPrice.objects.get_or_create(kind=kind, defaults={"first_tiyin": first * 100, "extra_tiyin": extra * 100})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verbose_names'),
        ('billing', '0002_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment', 'Payment system account (Payme / Click / Uzum)'), ('sms', 'SMS gateway account (Eskiz / Playmobile)')], max_length=10, unique=True)),
                ('first_tiyin', models.BigIntegerField(help_text='In tiyin: 1 soʻm = 100 tiyin.')),
                ('extra_tiyin', models.BigIntegerField(help_text='Each account after the first, in tiyin.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tariff price',
                'verbose_name_plural': 'tariff prices',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment', 'Payment system account (Payme / Click / Uzum)'), ('sms', 'SMS gateway account (Eskiz / Playmobile)')], max_length=10)),
                ('first_tiyin', models.BigIntegerField(help_text='In tiyin: 1 soʻm = 100 tiyin.')),
                ('extra_tiyin', models.BigIntegerField(help_text='Each account after the first, in tiyin.')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='accounts.company')),
            ],
            options={
                'verbose_name': 'special price',
                'verbose_name_plural': 'special prices',
                'constraints': [models.UniqueConstraint(fields=('company', 'kind'), name='uniq_company_tariff')],
            },
        ),
            migrations.RunPython(seed_prices, migrations.RunPython.noop),
    ]
