# Generated by Django 5.2.17 on 2026-09-24 20:28

from django.db import migrations, models


def seed_docs_price(apps, schema_editor):
    """Documents in amoCRM: 200 000 soʻm for the first amoCRM account, 100 000 for each more (editable)."""
    TariffPrice = apps.get_model("billing", "TariffPrice")
    TariffPrice.objects.get_or_create(kind="docs", defaults={"first_tiyin": 200_000 * 100, "extra_tiyin": 100_000 * 100})


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_tariff_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytariff',
            name='kind',
            field=models.CharField(choices=[('payment', 'Payment system account (Payme / Click / Uzum)'), ('sms', 'SMS gateway account (Eskiz / Playmobile)'), ('docs', 'Documents in amoCRM (per amoCRM account)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='kind',
            field=models.CharField(choices=[('payment', 'Payment system account (Payme / Click / Uzum)'), ('sms', 'SMS gateway account (Eskiz / Playmobile)'), ('docs', 'Documents in amoCRM (per amoCRM account)')], max_length=10, unique=True),
        ),
            migrations.RunPython(seed_docs_price, migrations.RunPython.noop),
    ]
