# Generated by Django 5.2.17 on 2026-09-24 20:56

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_docs_tariff'),
        ('amocrm', '0010_realty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('currency', models.CharField(choices=[('UZS', 'soʻm'), ('USD', 'USD')], default='UZS', max_length=3)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('sheet_key', models.CharField(default=secrets.token_urlsafe, max_length=43, unique=True)),
                ('sheet_url', models.URLField(blank=True, max_length=500)),
                ('showroom_key', models.CharField(default=secrets.token_urlsafe, max_length=43, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('show_sold_prices', models.BooleanField(default=False)),
                ('booking_hours', models.PositiveIntegerField(default=0)),
                ('use_in_amocrm', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realty_projects', to='accounts.company')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=40, verbose_name='ID in the sheet')),
                ('kind', models.CharField(choices=[('flat', 'Xonadon'), ('commercial', 'Tijorat'), ('office', 'Ofis'), ('parking', 'Parking'), ('storage', 'Omborxona'), ('townhouse', 'Taunxaus')], default='flat', max_length=12)),
                ('block', models.CharField(blank=True, max_length=60)),
                ('section', models.CharField(blank=True, max_length=60)),
                ('floor', models.IntegerField(default=1)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('rooms', models.PositiveSmallIntegerField(default=0)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('price_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('layout', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('free', 'Boʻsh'), ('interest', 'Qiziqish'), ('reserved', 'Band'), ('sold', 'Sotilgan'), ('closed', 'Sotuvda emas')], db_index=True, default='free', max_length=10)),
                ('sheet_status', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('plan_url', models.URLField(blank=True, max_length=500)),
                ('plan', models.BinaryField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=40)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('archived', models.BooleanField(default=False)),
                ('lead_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amo_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='amocrm.amoconnection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='realty.project')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'ordering': ['block', 'section', '-floor', 'number', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UnitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(blank=True, max_length=10)),
                ('status_to', models.CharField(max_length=10)),
                ('source', models.CharField(choices=[('sheet', 'Google Sheet'), ('amocrm', 'amoCRM'), ('site', 'uzbridge'), ('timer', 'Booking expired')], max_length=10)),
                ('lead_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='realty.unit')),
            ],
            options={
                'verbose_name': 'status change',
                'verbose_name_plural': 'status changes',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('project', 'ext_id'), name='uniq_unit_ext_id'),
        ),
    ]
