# Generated by Django 5.2.17 on 2026-09-24 21:33

import core.crypto
import django.db.models.deletion
import secrets
from django.db import migrations, models


def fill_tokens(apps, schema_editor):
    Project = apps.get_model("realty", "Project")
    for p in Project.objects.filter(pull_token=None):
        p.pull_token = secrets.token_urlsafe()
        p.save(update_fields=["pull_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_docs_tariff'),
        ('realty', '0001_realty'),
    ]

    operations = [
        # a distinct token per existing project, then unique
        migrations.AddField(
            model_name='project',
            name='pull_token',
            field=models.CharField(max_length=43, null=True),
        ),
        migrations.RunPython(fill_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='pull_token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=43, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sheet_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='sheet_tab',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('refresh_token', core.crypto.EncryptedTextField()),
                ('access_token', core.crypto.EncryptedTextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Google account',
            },
        ),
    ]
