# Generated by Django 5.2.17 on 2026-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='integration',
            field=models.CharField(db_index=True, default='api', max_length=20),
        ),
    ]
