# Generated by Django 5.2.17 on 2026-09-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_apikey_integration'),
        ('sms', '0005_multi_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='payment_accounts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='sms_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms.smsaccount'),
        ),
    ]
