# Generated by Django 5.2.17 on 2026-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_key_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'API key', 'verbose_name_plural': 'API keys'},
        ),
        migrations.AlterModelOptions(
            name='webhookdelivery',
            options={'ordering': ['-created_at'], 'verbose_name': 'webhook delivery', 'verbose_name_plural': 'webhook deliveries'},
        ),
        migrations.AlterModelOptions(
            name='webhookendpoint',
            options={'verbose_name': 'webhook endpoint', 'verbose_name_plural': 'webhook endpoints'},
        ),
    ]
