# Generated by Django 5.2.17 on 2026-09-24 09:46

import core.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ikpu_code', models.CharField(blank=True, max_length=17, verbose_name='MXIK / IKPU')),
                ('package_code', models.CharField(blank=True, max_length=20)),
                ('vat_percent', models.PositiveSmallIntegerField(default=12)),
                ('units', models.CharField(blank=True, max_length=20)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_defaults', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('amocrm', 'amoCRM')], default='manual', max_length=10)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('external_name', models.CharField(blank=True, max_length=255)),
                ('amount_tiyin', models.PositiveBigIntegerField()),
                ('currency', models.PositiveSmallIntegerField(default=860)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=10)),
                ('paid_via', models.CharField(blank=True, choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum Bank')], max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('crm_synced_at', models.DateTimeField(blank=True, null=True)),
                ('crm_sync_error', models.TextField(blank=True)),
                ('created_by_label', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum Bank')], max_length=10)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('test_mode', models.BooleanField(default=True)),
                ('merchant_id', models.CharField(blank=True, max_length=64)),
                ('service_id', models.CharField(blank=True, max_length=32)),
                ('merchant_user_id', models.CharField(blank=True, max_length=32)),
                ('secret', core.crypto.EncryptedTextField(blank=True)),
                ('test_secret', core.crypto.EncryptedTextField(blank=True)),
                ('auto_fiscal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_accounts', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum Bank')], max_length=10)),
                ('provider_txn_id', models.CharField(max_length=64)),
                ('amount_tiyin', models.PositiveBigIntegerField()),
                ('state', models.SmallIntegerField(default=1)),
                ('reason', models.SmallIntegerField(blank=True, null=True)),
                ('provider_time', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.provideraccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.invoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='provideraccount',
            constraint=models.UniqueConstraint(fields=('company', 'provider'), name='uniq_provider_account'),
        ),
        migrations.AddConstraint(
            model_name='providertransaction',
            constraint=models.UniqueConstraint(fields=('provider', 'account', 'provider_txn_id'), name='uniq_provider_txn'),
        ),
    ]
