# Generated by Django 5.2.17 on 2026-09-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideraccount',
            name='account_field',
            field=models.CharField(blank=True, default='order_id', max_length=32),
        ),
    ]
