# Generated by Django 5.2.17 on 2026-09-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payme_account_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
