# Generated by Django 5.2.17 on 2026-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_invoice_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='return_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('amocrm', 'amoCRM'), ('odoo', 'Odoo'), ('api', 'API')], default='manual', max_length=10),
        ),
    ]
