# Generated by Django 5.2.17 on 2026-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_invoice_return_url_alter_invoice_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('amocrm', 'amoCRM'), ('odoo', 'Odoo'), ('api', 'API'), ('topup', 'Balance top-up')], default='manual', max_length=10),
        ),
    ]
