# Generated by Django 5.2.17 on 2026-09-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_invoice_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amo_bill_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
