# Generated by Django 5.2.17 on 2026-09-24 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0007_multi_account'),
        ('developer', '0002_apikey_integration'),
        ('payments', '0006_bills_and_automation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provideraccount',
            options={'ordering': ['provider', 'created_at', 'pk']},
        ),
        migrations.RemoveConstraint(
            model_name='provideraccount',
            name='uniq_provider_account',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amo_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='amocrm.amoconnection'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='developer.apikey'),
        ),
        migrations.AddField(
            model_name='provideraccount',
            name='label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='provideraccount',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
