# Generated by Django 5.2.17 on 2026-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_multi_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldefaults',
            options={'verbose_name': 'fiscal defaults', 'verbose_name_plural': 'fiscal defaults'},
        ),
        migrations.AlterModelOptions(
            name='provideraccount',
            options={'ordering': ['provider', 'created_at', 'pk'], 'verbose_name': 'payment account', 'verbose_name_plural': 'payment accounts'},
        ),
        migrations.AlterModelOptions(
            name='providertransaction',
            options={'ordering': ['created_at'], 'verbose_name': 'provider transaction', 'verbose_name_plural': 'provider transactions'},
        ),
    ]
