# Generated by Django 5.2.17 on 2026-09-24 20:05

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_blocked_reason'),
        ('amocrm', '0009_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('docx', 'Uploaded Word file'), ('html', 'Built on the site')], max_length=10)),
                ('docx', models.BinaryField(blank=True, null=True)),
                ('docx_name', models.CharField(blank=True, max_length=200)),
                ('html', models.TextField(blank=True)),
                ('default_format', models.CharField(choices=[('docx', 'Word (.docx)'), ('pdf', 'PDF')], default='pdf', max_length=5)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('padding', models.PositiveSmallIntegerField(default=4)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('use_in_amocrm', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_templates', to='accounts.company')),
            ],
            options={
                'verbose_name': 'document template',
                'verbose_name_plural': 'document templates',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.BigIntegerField(db_index=True)),
                ('seq', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=40)),
                ('format', models.CharField(choices=[('docx', 'Word (.docx)'), ('pdf', 'PDF')], max_length=5)),
                ('content', models.BinaryField()),
                ('filename', models.CharField(max_length=200)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=43, unique=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('created_by_label', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amo_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='amocrm.amoconnection')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.company')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.doctemplate')),
            ],
            options={
                'verbose_name': 'generated document',
                'verbose_name_plural': 'generated documents',
                'ordering': ['-updated_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('template', 'seq'), name='uniq_doc_template_seq')],
            },
        ),
    ]
