# Generated by Django 5.2.17 on 2026-09-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctemplate',
            name='bindings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generateddoc',
            name='amo_file_format',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='generateddoc',
            name='amo_file_uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
