# Generated by Django 5.2.17 on 2026-09-24 09:46

import core.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(unique=True)),
                ('subdomain', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=150)),
                ('access_token', core.crypto.EncryptedTextField()),
                ('refresh_token', core.crypto.EncryptedTextField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Needs attention'), ('disconnected', 'Disconnected')], default='active', max_length=15)),
                ('last_error', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('pipelines', models.JSONField(blank=True, default=list)),
                ('pipelines_synced_at', models.DateTimeField(blank=True, null=True)),
                ('paid_stages', models.JSONField(blank=True, default=dict)),
                ('add_notes', models.BooleanField(default=True)),
                ('link_field_id', models.BigIntegerField(blank=True, null=True)),
                ('status_field_id', models.BigIntegerField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amocrm', to='accounts.company')),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
