# Generated by Django 5.2.17 on 2026-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0002_per_company_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoconnection',
            name='sms_field_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
