# Generated by Django 5.2.17 on 2026-09-24 16:28

import core.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0003_amoconnection_sms_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoconnection',
            name='widget_client_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='amoconnection',
            name='widget_client_secret',
            field=core.crypto.EncryptedTextField(blank=True),
        ),
    ]
