# Generated by Django 5.2.17 on 2026-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0004_widget_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoconnection',
            name='amo_providers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amoconnection',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
