# Generated by Django 5.2.17 on 2026-09-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0005_amocrm_widget_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoconnection',
            name='bills_catalog_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amoconnection',
            name='bills_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AmoAutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('link', 'Create payment link'), ('sms', 'Send SMS template'), ('link_sms', 'Create payment link, then send SMS')], max_length=10)),
                ('template_id', models.BigIntegerField(blank=True, null=True)),
                ('status_id', models.BigIntegerField(blank=True, null=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_jobs', to='amocrm.amoconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
