# Generated by Django 5.2.17 on 2026-09-24 17:27

import django.db.models.deletion
from django.db import migrations, models


def providers_to_accounts(apps, schema_editor):
    """amo_providers held provider codes; payment_accounts holds account ids."""
    Conn = apps.get_model("amocrm", "AmoConnection")
    Account = apps.get_model("payments", "ProviderAccount")
    for conn in Conn.objects.exclude(amo_providers=None):
        conn.payment_accounts = list(
            Account.objects.filter(company_id=conn.company_id, provider__in=conn.amo_providers).values_list("pk", flat=True)
        )
        conn.save(update_fields=["payment_accounts"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_single_session_usersession'),
        ('amocrm', '0006_bills_and_automation'),
        ('sms', '0004_sms_variables'),
        ('payments', '0006_bills_and_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoconnection',
            name='payment_accounts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amoconnection',
            name='sms_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms.smsaccount'),
        ),
        migrations.AlterField(
            model_name='amoconnection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amocrm_connections', to='accounts.company'),
        ),
        migrations.RunPython(providers_to_accounts, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='amoconnection',
            name='amo_providers',
        ),
    ]
