# Generated by Django 5.2.17 on 2026-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0007_multi_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amoautomationjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'automation job', 'verbose_name_plural': 'automation jobs'},
        ),
        migrations.AlterModelOptions(
            name='amoconnection',
            options={'verbose_name': 'amoCRM connection', 'verbose_name_plural': 'amoCRM connections'},
        ),
        migrations.AlterModelOptions(
            name='amoinstall',
            options={'verbose_name': 'connect attempt', 'verbose_name_plural': 'connect attempts'},
        ),
    ]
