# Generated by Django 5.2.17 on 2026-09-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0008_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoconnection',
            name='docs_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
