# Generated by Django 5.2.17 on 2026-09-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amocrm', '0009_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='amoconnection',
            name='field_group',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='amoconnection',
            name='realty_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amoconnection',
            name='realty_stages',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
