# Generated by Django 5.2.17 on 2026-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbacklog',
            options={'ordering': ['-created_at'], 'verbose_name': 'callback log', 'verbose_name_plural': 'callback logs'},
        ),
    ]
